-- MySQL Script generated by MySQL Workbench
-- Jum 08 Mar 2024 11:22:44 
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema payment_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payment_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payment_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `payment_db` ;

-- -----------------------------------------------------
-- Table `payment_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_db`.`user` ;

CREATE TABLE IF NOT EXISTS `payment_db`.`user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_db`.`account` ;

CREATE TABLE IF NOT EXISTS `payment_db`.`account` (
  `account_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `account_number` INT NOT NULL,
  `balance` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_account_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `payment_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_db`.`transaction` ;

CREATE TABLE IF NOT EXISTS `payment_db`.`transaction` (
  `transaction_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `date` DATE NOT NULL,
  state ENUM('pending', 'completed', 'failed', 'reversed') NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_transaction_1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `payment_db`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`virtual_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_db`.`virtual_account` ;

CREATE TABLE IF NOT EXISTS `payment_db`.`virtual_account` (
  `virtual_account_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `virtual_account_number` INT NOT NULL,
  PRIMARY KEY (`virtual_account_id`),
  INDEX `fk_virtual_account_1_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_virtual_account_1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `payment_db`.`transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
